# Generated by Django 3.2.3 on 2021-06-10 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_image_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Imagemodel',
        ),
    ]
