# Generated by Django 3.2.3 on 2021-07-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210712_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='input1',
        ),
        migrations.RemoveField(
            model_name='imagemodel',
            name='input2',
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='images',
            field=models.FileField(blank=True, upload_to='img/'),
        ),
    ]
